s

diff --git a/misc/remote-plan/env0.yml b/misc/remote-plan/env0.yml
--- a/misc/remote-plan/env0.yml
+++ b/misc/remote-plan/env0.yml
@@ -18,7 +18,16 @@ deploy:
 
         - name: terraform plan (as Local CLI User)
           run: terraform -chdir='./local-run' plan | tee plan-out.txt
-        - name: check for errors
+        - name: check for plan errors
           run: |
             ERRORS=`grep -c 'Error' plan-out.txt`
             if [ "$ERRORS" -eq "1" ]; then echo "plan failed" 1>&2 && exit 1; fi
+        - name: check if plan ran remotely
+          run: |
+            IS_REMOTE=`grep -c 'Running plan in the remote backend.' plan-out.txt`
+            if [ "$IS_REMOTE" -eq "0" ]; then echo "plan failed" 1>&2 && exit 1; fi
+        - name: check apply is not allowed for vcs connected workspaces
+          run: |
+            terraform -chdir='./local-run' apply || true | tee apply-out.txt
+            APPLY_ERROR_MESSAGE=`grep -c 'Apply not allowed for workspaces with a VCS connection' apply-out.txt`
+            if [ "$APPLY_ERROR_MESSAGE" -eq "0" ]; then echo "apply should fail but it didnt" 1>&2 && exit 1; fi
