s

diff --git a/misc/remote-plan/env0.yml b/misc/remote-plan/env0.yml
--- a/misc/remote-plan/env0.yml
+++ b/misc/remote-plan/env0.yml
@@ -17,8 +17,8 @@ deploy:
           run: terraform -chdir='./local-run' init
 
         - name: terraform plan (as Local CLI User)
-          run: terraform -chdir='./local-run' plan
-        - name: get environment
+          run: terraform -chdir='./local-run' plan > plan-out.txt
+        - name: Check if plan errored
           run: |
-            curl --location --request GET 'https://api-pr10727.dev.env0.com/environments?organizationId=1928f313-c72d-4f85-97a8-44c74858ebda&workspaceName=remote-plan-it3' \
-            --header 'Authorization: Bearer cmp6ZzY5ZTl0d2NsMmF4bjpZXzc1ZDFBV0hVQjhWREE1ajBwUDRMYnpST2FmUjRvXw==' > res.json
+            ERRORS=`grep -c 'Error' plan-out.txt`
+            if [ "$ERRORS" -eq "1" ]; then echo "plan failed" 1>&2 && exit 1; fi
